const std = @import("std");
const CodeWriter = @import("CodeWriter.zig");
const Command = @import("../generate_vk_wrappers.zig").Command;

fn generateFunctionBody(cw: *CodeWriter, command: *const Command) anyerror!void {
    const command_name = command.name orelse return error.NullCommandNameError;
    cw.enterIndent();
    defer cw.leaveIndent();

    switch (command.classify()) {
        .Instance => {
            const command_params = command.params orelse return error.MissingParams;
            if (command_params.len == 0) return error.MissingParams;
            const instance_param_name = command_params[0].getFieldName();

            cw.line("const state = instance_table.find(@ptrFromInt({s})) orelse {{", .{instance_param_name});
            cw.enterIndent();
            cw.line("std.debug.print(\"Could not find state for instance {{x}}\\n\", .{{{s}}});", .{instance_param_name});
            cw.line("return vk.c.VK_ERROR_UNKNOWN;");
            cw.leaveIndent();
            cw.line("}};");

            cw.line("const pfn = state.dispatch_table.{s};", .{command_name});
            cw.line("if (pfn == null) {{");
            cw.enterIndent();
            cw.line("std.debug.print(\"Function {s} not found in dispatch table\\n\", .{{@src().fn_name}});", .{command_name});
            cw.line("return vk.c.VK_ERROR_UNKNOWN;");
            cw.leaveIndent();
            cw.line("}}");

            cw.startLine();
            cw.print("const FnType = fn(", .{});
            for (command_params) |_| {
                cw.raw("usize,");
            }
            cw.raw(") usize;");
            cw.endLine();

            cw.line("const typed_pfn = @ptrCast(FnType, pfn);", .{});

            cw.startLine();
            cw.print("return typed_pfn(", .{});
            for (0.., command_params) |i, param| {
                if (i != 0) {
                    cw.raw(", ");
                }
                cw.print("{s}", .{param.getFieldName()});
            }
            cw.raw(");");
            cw.endLine();
        },
        else => {
            // std.debug.print("autogenerated vkCommandName({any}, {any})\n", .{param1, param2});")
            cw.startLine();
            cw.print("std.debug.print(\"autogenerated {s}(", .{command_name});
            if (command.params) |command_params| for (0.., command_params) |i, _| {
                if (i != 0) {
                    cw.raw(", ");
                }
                cw.raw("{any}");
            };
            cw.raw(")\\n\", .{");
            if (command.params) |command_params| for (0.., command_params) |i, param| {
                if (i != 0) {
                    cw.raw(", ");
                }
                cw.raw(param.getFieldName());
            };
            cw.raw("});");
            cw.endLine();

            cw.lineRaw("return 0;");
        },
    }
}

pub fn generateWrapperFunction(cw: *CodeWriter, wrapper_name: []const u8, command: *const Command) anyerror!void {
    cw.enterContextComment("generateWrapperFunction");
    defer cw.leaveContextComment("generateWrapperFunction");

    cw.startLine();
    cw.print("fn {s}(", .{wrapper_name});
    if (command.params) |command_params| for (0.., command_params) |i, param| {
        if (i != 0) {
            cw.raw(", ");
        }
        cw.print("{s}: usize", .{param.getFieldName()});
    };
    cw.raw(") usize {");
    cw.endLine();

    try generateFunctionBody(cw, command);

    cw.lineRaw("}");
}
