const std = @import("std");
const CodeWriter = @import("CodeWriter.zig");
const Command = @import("../generate_vk_wrappers.zig").Command;

pub fn generateWrapperFunction(cw: *CodeWriter, wrapper_name: []const u8, command: *const Command) anyerror!void {
    cw.enterContextComment("generateWrapperFunction");
    defer cw.leaveContextComment("generateWrapperFunction");

    cw.startLine();
    cw.print("fn {s}(", .{wrapper_name});
    if (command.params) |command_params| for (0.., command_params) |i, param| {
        if (i != 0) {
            cw.raw(", ");
        }
        cw.print("{s}: usize", .{param.getFieldName()});
    };
    cw.raw(") callconv(.C) isize {");
    cw.endLine();

    // Enter function's body
    cw.enterIndent();
    const command_name = command.name orelse return error.NullCommandNameError;

    // Write an autogenerated log of the command's arguments and name
    cw.startLine();
    cw.print("std.debug.print(\"autogenerated {s}(", .{command_name});
    if (command.params) |command_params| for (0.., command_params) |i, _| {
        if (i != 0) {
            cw.raw(", ");
        }
        cw.raw("{any}");
    };
    cw.raw(")\\n\", .{");
    if (command.params) |command_params| for (0.., command_params) |i, param| {
        if (i != 0) {
            cw.raw(", ");
        }
        cw.raw(param.getFieldName());
    };
    cw.raw("});");
    cw.endLine();

    // Find the dispatch table and call the original function.
    switch (command.classify()) {
        .Instance => {
            const command_params = command.params orelse return error.MissingParams;
            if (command_params.len == 0) return error.MissingParams;
            const instance_param_name = command_params[0].getFieldName();

            cw.line("const state = findInstance(@ptrFromInt({s})) orelse {{", .{instance_param_name});
            cw.enterIndent();
            cw.line("std.debug.print(\"Could not find state for instance {{x}}\\n\", .{{{s}}});", .{instance_param_name});
            cw.lineRaw("return vk.c.VK_ERROR_UNKNOWN;");
            cw.leaveIndent();
            cw.lineRaw("};");

            cw.line("const pfn = state.dispatch_table.{s};", .{command_name});
            cw.lineRaw("if (pfn == null) {");
            cw.enterIndent();
            cw.line("std.debug.print(\"Function {s} not found in dispatch table\\n\", .{{}});", .{command_name});
            cw.lineRaw("return vk.c.VK_ERROR_UNKNOWN;");
            cw.leaveIndent();
            cw.lineRaw("}");

            cw.startLine();
            cw.print("const typed_pfn: *const fn(", .{});
            for (0.., command_params) |i, _| {
                if (i != 0) {
                    cw.raw(", ");
                }
                cw.raw("usize");
            }
            cw.raw(") callconv(.C) isize = @ptrCast(pfn.?);");
            cw.endLine();

            cw.startLine();
            cw.print("return typed_pfn(", .{});
            for (0.., command_params) |i, param| {
                if (i != 0) {
                    cw.raw(", ");
                }
                cw.print("{s}", .{param.getFieldName()});
            }
            cw.raw(");");
            cw.endLine();
        },
        else => {
            // Default code gen: just return 0
            cw.lineRaw("return 0;");
        },
    }

    // End of function
    cw.leaveIndent();
    cw.lineRaw("}");
}
