const std = @import("std");
const CodeWriter = @import("CodeWriter.zig");
const Command = @import("../generate_vk_wrappers.zig").Command;

pub fn generateWrapperFunction(cw: *CodeWriter, wrapper_name: []const u8, command: *const Command) anyerror!void {
    cw.enterContextComment("generateWrapperFunction");
    defer cw.leaveContextComment("generateWrapperFunction");

    cw.startLine();
    cw.print("fn {s}(", .{wrapper_name});
    if (command.params) |command_params| for (0.., command_params) |i, param| {
        if (i != 0) {
            cw.raw(", ");
        }
        cw.print("{s}: usize", .{param.getFieldName()});
    };
    cw.raw(") usize {");
    cw.endLine();
    cw.enterIndent();

    // std.debug.print("autogenerated vkCommandName({any}, {any})\n", .{param1, param2});")
    cw.startLine();
    cw.print("std.debug.print(\"autogenerated {s}(", .{command.name orelse return error.NullCommandNameError});
    if (command.params) |command_params| for (0.., command_params) |i, _| {
        if (i != 0) {
            cw.raw(", ");
        }
        cw.raw("{any}");
    };
    cw.raw(")\\n\", .{");
    if (command.params) |command_params| for (0.., command_params) |i, param| {
        if (i != 0) {
            cw.raw(", ");
        }
        cw.raw(param.getFieldName());
    };
    cw.raw("});");
    cw.endLine();

    cw.leaveIndent();
    cw.lineRaw("}");
}
